apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap               
data:
  # db_server: "db.example.com"        # configmap key-value parameters
  # database: "mydatabase"
  # site.settings: |
  #   color=blue
  #   padding:25px
  
  nginx.cfg: |
    upstream backend {
        server app-1:8080;
        server app-2:8080;
    }

    server {
        location / {
            proxy_pass http://backend;
        }
    }